### ISSUE TITLE
Map with tags widget

### ISSUE THREAD

**Issue by oranyero** [ColdTrick/widget_pack#14]
An extension could be added with a map by coordinates and height, in which the tags with the URL to the pages or blogs of the site could be seen, where these tags can be added manually or associated, just as is done in image slideshow.

This could use https://leafletjs.com.

Thanks for maintaining the plugins. <3

**Comment by jdalsem** [comment]
Content in Elgg currently have no way to put the on the map (with the execption of some specific plugins), so there is no consistent data to add content on a map. Therefore we are not able to create such a widget.
