### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by insideth** [ColdTrick/widget_pack#3]
When composer update:

The requested package bower-asset/flexslider-customized could not be found in any version

**Comment by jdalsem** [comment]
It should exist (https://bower.io/search/?q=flexslider-customized)... did you install the ability for composer to download bower assets?

``composer global require "fxp/composer-asset-plugin:~1.1.4"``

**Comment by insideth** [comment]
Solved!, thanks Jeroen.
